services:
  db:
    container_name: sql
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: "Vuvietanh1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - cannabis-backend

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - cannabis-backend

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - cannabis-backend

networks:
  cannabis-backend:

volumes:
  sql_data: