FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src

# copy csproj để restore cache
COPY ["WebCannabisAccessorries.sln", "."]
COPY ["Cannabis.Server/Cannabis.Server.csproj", "Cannabis.Server/"]
COPY ["DAL/DAL.csproj","DAL/"]
COPY ["DTO/DTO.csproj","DTO/"]
COPY ["Enum/Enum.csproj","Enum/"]
COPY ["Exceptions/Exceptions.csproj","Exceptions/"]
COPY ["Middleware/Middleware.csproj","Middleware/"]
COPY ["Repository/Repository.csproj","Repository/"]
COPY ["Service/Service.csproj","Service/"]
COPY ["TestsCannabis/TestsCannabis.csproj","TestsCannabis/"]

RUN dotnet restore "Cannabis.Server/Cannabis.Server.csproj"

# ⚠️ KHÔNG cần COPY . .
# vì sẽ mount volume từ ngoài vào

WORKDIR /src/Cannabis.Server

EXPOSE 8080

ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=1

CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080"]