global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global  using  static Enum.Domain.Orders;
global  using  static Enum.Domain.Product_Inventory;
global  using  static Enum.Domain.System_User;
global  using  static Enum.Domain.TechnicalSpecs;
global using DAL.Inherited;
global using DAL.Entities;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.Extensions.Configuration;
