<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="IRepository\**" />
    <Compile Remove="Repository\**" />
    <EmbeddedResource Remove="IRepository\**" />
    <EmbeddedResource Remove="Repository\**" />
    <None Remove="IRepository\**" />
    <None Remove="Repository\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.14.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.6" />
    <PackageReference Include="MimeKit" Version="4.14.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.9.25" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DAL\DAL.csproj" />
    <ProjectReference Include="..\DTO\DTO.csproj" />
    <ProjectReference Include="..\Exceptions\Exceptions.csproj" />
    <ProjectReference Include="..\Repository\Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="IServices\Promotion\" />
    <Folder Include="IServices\Order\" />
  </ItemGroup>

</Project>
